DEFAULT_RETRIEVAL_STRATEGY = "hybrid"
DEFAULT_DENSE_TOP_K = 20
DEFAULT_SPARSE_TOP_K = 20
DEFAULT_RRF_K = 60
DEFAULT_RERANK_TOP_N = 5
DEFAULT_CHUNK_SIZE = 512
DEFAULT_CHUNK_OVERLAP = 64
DEFAULT_PARENT_CHILD_ENABLED = False
DEFAULT_PARENT_CHUNK_SIZE = 2048
DEFAULT_PARENT_CHUNK_OVERLAP = 128
DEFAULT_QUERY_LLM_TEMPERATURE = 0.2
DEFAULT_QUERY_LLM_MAX_TOKENS = 512
DEFAULT_QUERY_LLM_TIMEOUT = 15.0

QUERY_ENHANCEMENT_STRATEGIES = ["rewrite", "hyde", "multi_query"]

JINA_RERANK_TIMEOUT = 3.0
JINA_FALLBACK_PROVIDER = "passthrough"
