DEFAULT_RETRIEVAL_STRATEGY = "hybrid"
DEFAULT_RETRIEVAL_TOP_K = 20
DEFAULT_DENSE_CANDIDATE_TOP_K = 50
DEFAULT_SPARSE_CANDIDATE_TOP_K = 50
DEFAULT_DENSE_MIN_SCORE = 0.1
DEFAULT_SPARSE_MIN_TOKEN_OVERLAP = 1
DEFAULT_RRF_DENSE_WEIGHT = 1.0
DEFAULT_RRF_SPARSE_WEIGHT = 0.6
DEFAULT_PER_KB_SAFETY_CAP = 80
DEFAULT_FUSION_CANDIDATE_TOP_K = 50
DEFAULT_RRF_K = 60
DEFAULT_CHUNK_SIZE = 512
DEFAULT_CHUNK_OVERLAP = 64
DEFAULT_PARENT_CHILD_ENABLED = False
DEFAULT_PARENT_CHUNK_SIZE = 2048
DEFAULT_PARENT_CHUNK_OVERLAP = 128
DEFAULT_QUERY_LLM_TEMPERATURE = 0.2
DEFAULT_QUERY_LLM_MAX_TOKENS = 512
DEFAULT_QUERY_LLM_TIMEOUT = 15.0

QUERY_ENHANCEMENT_STRATEGIES = ["rewrite", "hyde", "multi_query"]

JINA_RERANK_TIMEOUT = 3.0
JINA_FALLBACK_PROVIDER = "passthrough"
